# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bpm', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('artists', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('audio', models.FileField(upload_to=b'')),
                ('art', models.ImageField(upload_to=b'')),
                ('spectrogram', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Top100Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bpm', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
                ('audio_url', models.URLField()),
                ('label', models.CharField(max_length=50)),
                ('artists', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('key', models.TextField()),
                ('index', models.IntegerField()),
            ],
        ),
    ]
